# Generated by Django 3.1.4 on 2021-01-13 21:36

import core.validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='', validators=[core.validator.validate_file_extension])),
                ('file0', models.FileField(upload_to='')),
                ('file1', models.FileField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('spec', models.CharField(choices=[('Engineering', 'Engineering'), ('Science', 'Science'), ('Arts', 'Arts'), ('Education', 'Education'), ('Humanities', 'Humanities')], default='Engineering', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('start', models.CharField(choices=[('ko-KR', 'Korean'), ('en-US', 'English')], default='ko-KO', max_length=10)),
                ('arrive', models.CharField(choices=[('en', 'English'), ('ko', 'Korean'), ('zh', 'Chinese'), ('fr', 'French'), ('es', 'Spanish'), ('kk', 'Kazakh')], default='en', max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('encoded', models.BooleanField(default=False)),
                ('predict', models.DateTimeField()),
                ('predictstr', models.TextField()),
                ('deletewarn', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
